---
# tasks file for nginx
- name: install nginx package on RadHat
  yum:
    name: nginx
    state: present
  when: ansible_os_family == "RadHat"
  become: yes

- name: install nginx package on Debian
  apt:
    name: nginx
    state: present
  when: ansible_os_family == "Debian"
  become: yes
- name: ensure nginx is enabled and runing
  service:
    name: nginx
    state: started
    enabled: true

- name: disable default site if required
  file:
   path: /etc/nginx/sites-enabled/default
   state: absent
  when: not nginx_default_sites_enabled
  become: yes

- name: deploy nginx configuration file
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_path }}"
    owner: root
    group: root
    mode: '0644'
    beckup: yes
  notify:
    - reload: nginx
  become: yes
