---
# tasks file for test_1

#- name: update apt
#  apt:
#    update_cache: yes
#  become: yes
#  become_user: root

#- name: install softwear
#  apt:
#    name: "{{ item }}"
#    state: present
#    update_cache: yes
#  loop:
#    - "{{ packages }}"
#  become: yes
#  become_user: root
- name: get swap path
  shell: swapon --show
  register: swap_path

- name: print swap path
  debug:
    var: swap_path

- name: load average
  shell: 'uptime | awk -F"load average: " "{print \$2}"'
  register: uptime_average

- name: print load average with label
  debug:
    msg: "load average: {{ uptime_average.stdout }}"

